event_registration.settings:
  type: config_object
  label: "Event Registration settings"
  mapping:
    admin_email:
      type: string
      label: "Administrator email address"
    enable_admin_notifications:
      type: boolean
      label: "Enable admin notifications"
    notification_email_subject:
      type: string
      label: "Notification email subject"
